### ISSUE TITLE
Requirements mismatch

### ISSUE THREAD

**Issue by grahamperrin** [vfrico/firefox-breeze-duo#1]
https://github.com/vfrico/firefox-breeze-duo/blob/081c68ca4a5aadca509716cb2150d9788745fd71/README.md#breeze-duo-theme-for-firefox

> … Firefox 60 …

https://addons.mozilla.org/addon/breeze-duo/versions/?page=1#version-1.3

>  Works with Firefox for Android 48.0 and later, Firefox 48.0 and later

**Comment by vfrico** [comment]
Thanks to pointing it out. It is my first web extension and I didn't knew those kind of details.

I've corrected on [MOS](https://addons.mozilla.org/en-US/firefox/addon/breeze-duo/versions/?page=1#version-1.3).

**Comment by grahamperrin** [comment]
Thanks :+1:
