### ISSUE TITLE
No window buttons when title bar is disabled

### ISSUE THREAD

**Issue by bllngr** [vfrico/firefox-breeze-duo#2]
I'm using Firefox 62 on Plasma 5.13 with the Breeze theme. In Firefox, I've disabled the title bar via _hamburger menu > Customize... >_ uncheck _"Title Bar"_ in the bottom left.

With this configuration, the Maximize/Minimize/Close buttons are not shown. The close buttons appears on mouse over, the others don't appear at all.

**Comment by vfrico** [comment]
Ok, I'll take a look as soon as possible.
Thanks for reporting

**Comment by bllngr** [comment]
Anything new on this issue? I just noticed that it may happen only on Breeze Dark, but it also happens with Breeze light. Strangely enough, the titlebar will be dark with Breeze light as well.

**Comment by vfrico** [comment]
I've looking for a solution to this issue, but it does not seem to be easy to solve, as Firefox does not provide any API to change the colors of the close, minimize and maximize buttons...

**Comment by Mte90** [comment]
![immagine](https://user-images.githubusercontent.com/403283/50764803-2e12c880-1274-11e9-852b-bd736641fbc5.png)
Only on hover the button to close is showed and right now seems very uncomfortable.

**Comment by vfrico** [comment]
> ![immagine](https://user-images.githubusercontent.com/403283/50764803-2e12c880-1274-11e9-852b-bd736641fbc5.png)
> Only on hover the button to close is showed and right now seems very uncomfortable.

I still don't know how to workaround this issue.

**Comment by Mte90** [comment]
I am wondering if it is a problem of firefox or of KDE.
Just the fact that happen only with an icon for me is firefox.
I will share to the Firefox Addon team this ticket and invite them to join the discussion.

**Comment by vfrico** [comment]
I think that this issue is just that this theme's background color is exactly the same as the close buttons, and they are only visible when you hover them (because the color of the button itself changes)

**Comment by bllngr** [comment]
I finally found the culprit! The window buttons are rendered by the GTK CSD, which uses the GTK3 theme. On my system, the GTK3 theme was set to Breeze, which by default shows dark buttons on a light background. breeze-duo now changes the background color to the same dark gray, which makes the buttons in fact disappear.

Setting the GTK3 theme to _Breeze Dark_ forces a dark CSD titlebar, and thus light window buttons. This can be done either globally via _System Settings > Application Style > GNOME Application Style_ and selecting the Breeze-Dark GTK3 theme, or only for firefox by starting it with ``GTK_THEME=Breeze-Dark firefox``.

**Comment by Mte90** [comment]
Yes, you are right @sqrt this fix the problem!

**Comment by bllngr** [comment]
I've filed a feature request for breeze-gtk at https://bugs.kde.org/show_bug.cgi?id=404921. So from my point of view, this issue can be closed, @vfrico. :)

**Comment by vfrico** [comment]
@sqrt Thank you very much!!

**Comment by teaqu** [comment]
Run this command in the terminal to fix the buttons and retain the light theme for everything else such as inputs, scrollbar, etc.

`yes | (mkdir -p ~/.themes && (cp -r /usr/share/themes/Breath/ ~/.themes/Breeze-Firefox || cp -r /usr/share/themes/Breeze/ ~/.themes/Breeze-Firefox)  && (cp -r /usr/share/themes/Breath-Dark/assets/title* ~/.themes/Breeze-Firefox/assets || cp -r /usr/share/themes/Breeze-Dark/assets/title* ~/.themes/Breeze-Firefox/assets) && cp -r /usr/share/applications/firefox.desktop ~/.local/share/applications/firefox.desktop && sed -i 's/Exec=/Exec=GTK_THEME=Breeze-Firefox /g' ~/.local/share/applications/firefox.desktop) && echo "alias firefox=\"GTK_THEME=Breeze-Firefox firefox\"" >> ~/.bashrc`
